jobs:
  - name: basic-node-test
    type: runSh
    steps:
      - TASK:
        name: delivery_container_pull
        script:
          - docker pull alpine:3.7
      - TASK:
          name: run_hw
          runtime:
            options:
              imageName: alpine
              imageTag: '3.7'
              pull: false
          script:
            - echo "Hello World"
  - name: basic-node-test_runCI
    type: runCI
    steps:
      - TASK:
        name: delivery_container_pull
        script:
          - docker pull alpine:3.7
      - TASK:
          name: run_hw
          runtime:
            options:
              imageName: alpine
              imageTag: '3.7'
              pull: false
          script:
            - echo "Hello CI"