jobs:
  - name: basic-node-test
    type: runSh
    steps:
      - IN: basic-node-vars
      - TASK:
          name: run_hw
          runtime:
            options:
              imageName: alpine
              imageTag: '3.7'
              pull: false
          script:
            - echo "Hola Mundo"